/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FalecidosIndexRouteImport } from './routes/falecidos/index'
import { Route as FalecidosFalecidoIdRouteImport } from './routes/falecidos/$falecidoId'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FalecidosIndexRoute = FalecidosIndexRouteImport.update({
  id: '/falecidos/',
  path: '/falecidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const FalecidosFalecidoIdRoute = FalecidosFalecidoIdRouteImport.update({
  id: '/falecidos/$falecidoId',
  path: '/falecidos/$falecidoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/falecidos/$falecidoId': typeof FalecidosFalecidoIdRoute
  '/falecidos/': typeof FalecidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/falecidos/$falecidoId': typeof FalecidosFalecidoIdRoute
  '/falecidos': typeof FalecidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/falecidos/$falecidoId': typeof FalecidosFalecidoIdRoute
  '/falecidos/': typeof FalecidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sobre' | '/falecidos/$falecidoId' | '/falecidos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sobre' | '/falecidos/$falecidoId' | '/falecidos'
  id: '__root__' | '/' | '/sobre' | '/falecidos/$falecidoId' | '/falecidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SobreRoute: typeof SobreRoute
  FalecidosFalecidoIdRoute: typeof FalecidosFalecidoIdRoute
  FalecidosIndexRoute: typeof FalecidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/falecidos/': {
      id: '/falecidos/'
      path: '/falecidos'
      fullPath: '/falecidos/'
      preLoaderRoute: typeof FalecidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/falecidos/$falecidoId': {
      id: '/falecidos/$falecidoId'
      path: '/falecidos/$falecidoId'
      fullPath: '/falecidos/$falecidoId'
      preLoaderRoute: typeof FalecidosFalecidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SobreRoute: SobreRoute,
  FalecidosFalecidoIdRoute: FalecidosFalecidoIdRoute,
  FalecidosIndexRoute: FalecidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
